const ACTION_TYPES = {
    INPUT_ENTRY: 'INPUT_ENTRY',
    // SEARCH_USER = 'SEARCH_USER',
    SET_USERNAME: 'SET_USERNAME',
    // SEARCH_EVENTS = 'SEARCH_EVENTS',
    SET_FORKS: 'SET_FORKS',
    SET_PULL_REQUESTS: 'SET_PULL_REQUESTS',
    RESET_USER: 'RESET_USER'
}

export default ACTION_TYPES;